# Generated by Django 2.1.1 on 2018-09-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=10)),
                ('data_zapuska', models.DateField()),
                ('vmestimost', models.IntegerField()),
                ('bazovoe_obraz', models.CharField(max_length=100)),
                ('forma_obucheniya', models.CharField(max_length=50)),
                ('srok_god', models.IntegerField()),
                ('srok_mes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kompetencii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10)),
                ('naimenovanie', models.CharField(max_length=255)),
                ('kvalifikaciya', models.CharField(max_length=255)),
                ('rab_professii', models.CharField(max_length=255)),
                ('uroven_podgotovki', models.CharField(max_length=255)),
                ('top50_58', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('otch', models.CharField(max_length=50)),
                ('birsday', models.DateField()),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='kompetenciya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolledg.Kompetencii'),
        ),
    ]
